name: core_haptics
description: Type-safe Core Haptics FFI plugin (iOS & macOS) via SwiftPM.
version: 0.1.0

homepage: https://github.com/Azzeccagarbugli/core_haptics
issue_tracker: https://github.com/Azzeccagarbugli/core_haptics/issues

topics:
  - haptics
  - vibration
  - ahap

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3

flutter:
  plugin:
    platforms:
      ios:
        dartPluginClass: CoreHapticsPlugin
      macos:
        dartPluginClass: CoreHapticsPlugin
